'use strict';

/* Controllers */

var canucksApp = angular.module('canucksApp', []);

canucksApp.controller('PlayersController', function($scope) {
  $scope.players = [
    {'name': 'Nick Bonino',
     'position': 'Center Forward',
     'img': './img/bonino.jpg',
     'age': 25,
     'number' : 1},
    {'name': 'Alexandre Burrows',
     'position': 'Right Wing',
     'img': './img/burrows.jpg',
     'age': 27,
     'number' : 2},
    {'name': 'Derek Dorsett',
     'position': 'Right Wing',
     'img': './img/dorsett.jpg',
     'age': 32,
     'number' : 3},
    {'name': 'Jannik Hansen',
     'position': 'Right Wing',
     'img': './img/hansen.jpg',
     'age': 28,
     'number' : 4},
    {'name': 'Chris Higgins',
     'position': 'Left Wing',
     'img': './img/higgins.jpg',
     'age': 25,
     'number' : 5},
    {'name': 'Bo Horvat',
     'position': 'Center Forward',
     'img': './img/horvat.jpg',
     'age': 24,
     'number' : 6},
    {'name': 'Zack Kassian',
     'position': 'Right Wing',
     'img': './img/kassian.jpg',
     'age': 27,
     'number' : 7},
    {'name': 'Shawn Matthias',
     'position': 'Center Forward',
     'img': './img/matthias.jpg',
     'age': 26,
     'number' : 8},
    {'name': 'Brad Richardson',
     'position': 'Right Wing',
     'img': './img/richardson.jpg',
     'age': 32,
     'number' : 9},
    {'name': 'Daniel Sedin',
     'position': 'Left Wing',
     'img': './img/dsedin.jpg',
     'age': 32,
     'number' : 22},
    {'name': 'Hendrik Sedin',
     'position': 'Center Forward',
     'img': './img/hsedin.jpg',
     'age': 25,
     'number' : 33},
    {'name': 'Linden Vey',
     'position': 'Right Wing',
     'img': './img/vey.jpg',
     'age': 29,
     'number' : 12},
    {'name': 'Radim Vrbata',
     'position': 'Right Wing',
     'img': './img/vrbata.jpg',
     'age': 29,
     'number' : 13},
    {'name': 'Kevin Bieksa',
     'position': 'Defenceman',
     'img': './img/bieksa.jpg',
     'age': 27,
     'number' : 14},
    {'name': 'Alexander Edler',
     'position': 'Defenceman',
     'img': './img/edler.jpg',
     'age': 33,
     'number' : 15},
    {'name': 'Dan Hamhuis',
     'position': 'Defenceman',
     'img': './img/hamhuis.jpg',
     'age': 23,
     'number' : 16},
    {'name': 'Luca Sbisa',
     'position': 'Defenceman',
     'img': './img/sbisa.jpg',
     'age': 27,
     'number' : 17},
     {'name': 'Ryan Stanton',
     'position': 'Defenceman',
     'img': './img/stanton.jpg',
     'age': 26,
     'number' : 18},
     {'name': 'Christopher Tanev',
     'position': 'Defenceman',
     'img': './img/tanev.jpg',
     'age': 25,
     'number' : 19},
     {'name': 'Yannick Weber',
     'position': 'Defenceman',
     'img': './img/weber.jpg',
     'age': 24,
     'number' : 20},
     {'name': 'Eddie Lack',
     'position': 'Goalie',
     'img': './img/lack.jpg',
     'age': 23,
     'number' : 21},
     {'name': 'Ryan Miller',
     'position': 'Goalie',
     'img': './img/miller.jpg',
     'age': 20,
     'number' : 31},
  ];

  $scope.orderProp = 'age';
});